AWSTemplateFormatVersion: 2010-09-09
Transform: AWS::Serverless-2016-10-31

Outputs:
  HttpApi:
    Value: !Ref ServerlessHttpApi

Resources:
  HelloWorldFunction:
    Type: AWS::Serverless::Function
    Properties:
      Events:
        HttpApiEvent:
          Type: HttpApi
          Properties:
            Method: GET
            Path: /
      CodeUri: src/helloworld/
      Handler: api.handler
      Runtime: python3.8
