version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.8
  build:
    commands:
      - pip install -r requirements-test.txt
      - flake8 src
      - mypy src
      - black src --check
      - pytest tests/unit
      - ./deploy.sh serverless-template-python-test
      - STACK_NAME=serverless-template-python-test pytest tests/integration
